# Copyright (c) 2025 The ZMK Contributors
# SPDX-License-Identifier: MIT

# -----------------------------------
# Power + Sleep Behaviour
# -----------------------------------
CONFIG_ZMK_SLEEP=n
# stay awake for 1hr idle
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=3600000

# -------------------------------------------------
# Keyscan Tuning
# -------------------------------------------------
# Longer debounce -> more stability, less "chatter"
CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=8
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=8